# Generated by Django 3.2.16 on 2024-05-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=300, verbose_name='Короткое описание новости')),
                ('content', models.TextField(verbose_name='Текст новости')),
                ('image', models.ImageField(upload_to='news-images/', verbose_name='Картинка новости')),
                ('published_date', models.DateField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-published_date',),
            },
        ),
    ]
